const wordlist = [
  { word: "air", hint: "the invisible gas" },
  { word: "idea", hint: "a thought or suggestion" },
  { word: "server", hint: "related to computer and system" },
  { word: "search", hint: "act to find something" },
  { word: "cloud", hint: "a visible mass of condensed vapor" },
  { word: "code", hint: "a system of words or symbols" },
  { word: "data", hint: "facts and statistics collected for analysis" },
  { word: "file", hint: "a collection of information stored on a computer" },
  { word: "link", hint: "a reference to a document or resource" },
  { word: "byte", hint: "a unit of digital information" },
  { word: "host", hint: "a server that provides services to clients" },
  { word: "query", hint: "a request for information from a database" },
  { word: "token", hint: "a piece of data representing a user's identity" },
  { word: "cache", hint: "temporary storage for quick data access" },
  { word: "debug", hint: "to identify and remove errors from software" },
];
